#!/usr/bin/env python3

import numpy as np

cross_entropy = lambda y, p: -(y*np.log(p) + (1-y)*np.log(1-p))

y = np.array([1, 0, 1, 0])
p = np.array([0.9, 0.1, 0.2, 0.8])

loss = cross_entropy(y, p)
print(loss)
print('mean loss:', loss.mean())
