#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression
import os

X, y = make_blobs(n_samples=600, centers=3, cluster_std=1.2, random_state=0)

clf = LogisticRegression(multi_class='multinomial', solver='lbfgs')
clf.fit(X, y)

x_min, x_max = X[:,0].min() - 1, X[:,0].max() + 1
y_min, y_max = X[:,1].min() - 1, X[:,1].max() + 1

xx, yy = np.meshgrid(
    np.linspace(x_min, x_max, 400),
    np.linspace(y_min, y_max, 400)
)

grid = np.c_[xx.ravel(), yy.ravel()]
Z = clf.predict(grid).reshape(xx.shape)

plt.contourf(xx, yy, Z, alpha=0.4)
plt.scatter(X[:,0], X[:,1], c=y)
path = '/tmp/tvtoMultiClassBoundary.png'
plt.savefig(path, dpi=150, bbox_inches='tight')
os.system(f'xdg-open {path}')
