#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
import os

sigmoid = lambda z: 1 / (1 + np.exp(-z))

z = np.linspace(-10, 10, 400)
s = sigmoid(z)

plt.plot(z, s)
plt.xlabel('z')
plt.ylabel('sigmoid(z)')
plt.grid(True)

path = '/tmp/tvtoSigmoidFunction.png'
plt.savefig(path, dpi=150, bbox_inches='tight')

os.system(f'xdg-open {path}')
